name: marwa_teacher
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio:
  shared_preferences:
  flutter_bloc:
  bloc:
  flutter_onboard:
  conditional_builder_null_safety:
  carousel_slider: ^5.0.0
  buttons_tabbar: ^1.3.10
  sqflite:
  url_launcher:
  intl:
  image_picker:
  lottie:
  http_parser: ^4.0.2
  top_snackbar_flutter: ^3.2.0
  onesignal_flutter: ^5.3.0
  fw_tab_bar: ^0.0.3
  animated_text_kit: ^4.2.2
  video_player: ^2.9.2
  chewie: ^1.10.0
  file_picker:
  tus_client: ^1.0.2
  google_nav_bar: ^5.0.7
  font_awesome_flutter: ^10.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/Cairo/static/Cairo-Bold.ttf
